# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b92e679860429f8e84239e938245b2802ab9c40f5e26e37fe783b21cee3ee5b7fa056442a21f37bd80c13a26573c6d5f9811aacdc757befe897f8070c6743844

test:
  secret_key_base: 2295f2f73670eb85749a62d7dfc0abdc46f955e2ea40f44cf33a163acff92461e669920412514f1058358d99c31d77bb20aa17606e015974f37a8c7a15373109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
